### ISSUE TITLE
net.kuujo.copycat.netty.NettyTcpProtocolClient$1 is not a @Sharable handler, so can't be added or removed multiple times

### ISSUE THREAD

**Issue by pizirun** [kuujo/copycat#20]
(on master branch)
2015-03-09 00:06:51,148 WARN  [io.netty.channel.ChannelInitializer] (nioEventLoopGroup-8-1:) Failed to initialize a channel. Closing: [id: 0xa96c6eff]
io.netty.channel.ChannelPipelineException: net.kuujo.copycat.netty.NettyTcpProtocolClient$1 is not a @Sharable handler, so can't be added or removed multiple times.
	at io.netty.channel.DefaultChannelPipeline.checkMultiplicity(DefaultChannelPipeline.java:463)
	at io.netty.channel.DefaultChannelPipeline.addLast0(DefaultChannelPipeline.java:135)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:128)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:119)
	at net.kuujo.copycat.netty.NettyTcpProtocolClient$2.initChannel(NettyTcpProtocolClient.java:133)
	at net.kuujo.copycat.netty.NettyTcpProtocolClient$2.initChannel(NettyTcpProtocolClient.java:122)
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:443)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:375)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:419)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)

The sample code:
public static void main(String[] args) {
        ClusterConfig cluster = new ClusterConfig()
                .withProtocol(new NettyTcpProtocol())
                .withLocalMember("tcp://192.168.9.207:5004")
                .withMembers("tcp://192.168.9.207:5000", "tcp://192.168.9.207:5001", "tcp://192.168.9.207:5002"
                , "tcp://192.168.9.207:5003", "tcp://192.168.9.207:5004");
        
        LeaderElection.create("election", cluster).open().thenAccept(election -> {
            election.addListener(member -> {
                System.out.println(member.uri() + " was elected leader!");
            });
        });
    }

**Comment by pizirun** [comment]
After switch to local protocol, still not success:
2015-03-09 00:43:15,596 WARN  [net.kuujo.copycat.raft.FollowerState] (copycat-coordinator:) local://foo
java.util.concurrent.CompletionException: net.kuujo.copycat.protocol.ProtocolException: Invalid server address bar
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1969)
	at net.kuujo.copycat.cluster.internal.coordinator.DefaultRemoteMemberCoordinator.lambda$send$70(DefaultRemoteMemberCoordinator.java:66)
	at net.kuujo.copycat.cluster.internal.coordinator.DefaultRemoteMemberCoordinator$$Lambda$69/1680852222.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


public static void main(String[] args) throws InterruptedException {
        ClusterConfig cluster = new ClusterConfig()
                .withProtocol(new LocalProtocol())
                .withMembers("local://foo", "local://bar", "local://baz");

        LeaderElection.create("election", cluster.copy().withLocalMember("local://foo")).open().thenAccept(election -> {
            election.addListener(member -> {
                System.out.println(member.uri() + " was elected leader!");
            });
        });

        TimeUnit.SECONDS.sleep(30L);
    }


The unit test LeaderElectionTest is passed, btw.

**Comment by aqualuk** [comment]
Hi,

I have the same problem. Is there any solution for this issue?

Thanks.

**Comment by kuujo** [comment]
Hmm... Should be an easy fix... It shouldn't be using a singleton handler.

There were issues with that Netty implementation. This will actually be fixed in the upcoming first release, but I don't expect it to be stable for a couple weeks.

I would say, don't get too dependent on the code in the master branch. It will never be released. The final API will be stable within a couple days, and probably merged in to master in a week. I am going to put a note about the coming changes (primarily simplifying and solidifying the API) in the README.

**Comment by juaby** [comment]
I have the same problem. i know

**Comment by juaby** [comment]
ClusterConfig clusterConfig = new ClusterConfig()
                .withProtocol(new NettyTcpProtocol())
                .withLocalMember("tcp://10.12.115.29:5001")
                .withMembers(
                        "tcp://10.12.115.29:5001",
                        "tcp://10.12.115.29:5002",
                        "tcp://10.12.115.29:5003"
                );

        CopycatConfig config = new CopycatConfig()
                .withClusterConfig(clusterConfig);

        Copycat copycat = Copycat.create(config);

        copycat.open()
                .thenCompose(c -> c.createLeaderElection("election").open())
                .thenAccept(election -> {
                    election.addListener(member -> System.out.println(member.uri() + " was elected leader!"));
                });
        System.out.println("what ! " + copycat.cluster().member().type().name());


run three jvm instance，
and output ：what ! ACTIVE
and why not output  member.uri() + " was elected leader!"
thans!

**Comment by juaby** [comment]
java8 hard to understand

**Comment by kuujo** [comment]
The `0.6.0` branch has been merged into `master` and is significantly more stable than the previous development branch. This is no longer an issue.
